# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb",
         "load_data": "03_process_data.ipynb",
         "tokenize": "02_run.ipynb",
         "build_model": "01_train_classifier.ipynb",
         "evaluate_model": "01_train_classifier.ipynb",
         "save_model": "01_train_classifier.ipynb",
         "main": "03_process_data.ipynb",
         "app": "02_run.ipynb",
         "engine": "02_run.ipynb",
         "df": "02_run.ipynb",
         "model": "02_run.ipynb",
         "index": "02_run.ipynb",
         "go": "02_run.ipynb",
         "clean_data": "03_process_data.ipynb",
         "save_data": "03_process_data.ipynb"}

modules = ["core.py",
           "train_classifier.py",
           "run.py",
           "process_data.py"]

doc_url = "https://Minh.github.io/nbdev_disaster_recovery_lib/"

git_url = "https://github.com/Minh/nbdev_disaster_recovery_lib/tree/master/"

def custom_doc_links(name): return None
